server:
  port: 60006

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
    open-in-view: false
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ENC(cw1Xv4VHESL5EoFrPKhuO1te2FYiqmkQhBJssnuAuKM73JK7LqhUxVkqlLBzZs/b)
    username: ENC(8kFHBv/0LPMT1tsnOEfAnA==)
    password: ENC(rQGhzeAG2gi94UXhSUebLXsxpAi8Torr)

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: 2^!2K"Gy=9ThPXE
