server:
  port: 60006


spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
    open-in-view: false
#  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://localhost:3306/db23206
#    username: dbid232
#    password: dbpass232
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:homemate
    username: root
    password: 1234
    driver-class-name: org.h2.Driver
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: GlRRzCrwLEtzQw_l6iMO
            client-secret: GxpKohcy7M
#            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            redirect-uri: http://ceprj.gachon.ac.kr:60006/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope: name, email
            client-name: Naver

          kakao:
            client-id: e7ddd0b4b6b094437e32ead506281677
            client-secret: w3TuYpxLScw9uEW4BmB6dDGhGZqCvYvh
#            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            redirect-uri: http://ceprj.gachon.ac.kr:60006/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: account_email
            client-name: Kakao

        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

logging.level:
  org.hibernate.SQL: debug

jwt:
  secretKey: hj3224hjlk3h4j3

  access:
    expiration: 3600000 # 1시간(60분) (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h))
    header: Authorization

  refresh:
    expiration: 1209600000 #  (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h) * 24L(h -> 하루) * 14(2주))
    header: Authorization-refresh